function nonGroundPoints = getNonGroundSMRF(pointCloud)
    [~,nonGroundPoints,~] = segmentGroundSMRF(pointCloud, 1, ...
        "MaxWindowRadius",18, ...
        "SlopeThreshold",0.15, ...
        "ElevationThreshold",0.03, ...
        "ElevationScale",1.25);
end